---
new_page_extension: md
auto_deploy: false
admin_path: unruly-web
webhook_url: 
sections:
- type: heading
  label: Unruly Chain
- type: document
  path: ipfs
  label: IPFS
- type: document
  path: smart-contracts
  label: Smart Contracts
- type: document
  path: vpn
  label: Decentralized VPNs
- type: document
  path: counter-analytics
  label: Blockchain Counter-Analytics
- type: document
  path: content/data/info.json
  label: About
- type: heading
  label: General Config
- type: document
  path: config.json
  label: Site Info
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: yarn forestry-preview
